---
- name: Launch EC2 instance, get public IP, and install Nginx
  hosts: localhost
  tasks:
    - amazon.aws.ec2_instance:
        name: "public-compute-instance"
        access_key: accesskey
        secret_key: secretkey
        key_name: "ansible"
        vpc_subnet_id: subnet-00009cc64bb842e77	
        instance_type: t3.micro
        security_group: default
        network:
          assign_public_ip: true
        image_id: ami-053b0d53c279acc90
        tags:
          Environment: Testing
      register: ec2
    - name: Disable Root Login
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'

    - name: Create SSH Group to login dynamically to EC2 Instance
      add_host: 
        hostname: "34.235.131.96"
        ansible_ssh_private_key_file: /home/dikshant/Documents/zeerodha-task/Devops-Task-Zeerodha/ops-interview-task-master/ansible/ansible.pem
        groupname: ec2_server
      with_items: ec2.instances

    - name: Wait for SSH to come up
      wait_for: 
        host: "34.235.131.96" 
        port: 22 
        state: started
      with_items: ec2.instances

    - name: Install Nginx
      become: yes
      ansible.builtin.shell: "sudo apt-get update && sudo apt-get install -y nginx"
      delegate_to: "34.235.131.96"
      remote_user: "ubuntu"

    - name: Allow SSH and enable UFW
      become: yes
      ansible.builtin.shell: |
        sudo ufw allow OpenSSH
        sudo ufw --force enable
      delegate_to: "34.235.131.96"
      remote_user: "ubuntu"

    - name: Increase Open Files Limit
      become: yes
      ansible.builtin.sysctl:
        name: fs.file-max
        value: 65536
      delegate_to: "34.235.131.96"
      remote_user: "ubuntu"

    - name: Change Kernel PID Max
      become: yes
      ansible.builtin.sysctl:
        name: kernel.pid_max
        value: 65535
      delegate_to: "34.235.131.96"
      remote_user: "ubuntu"
    

    - name: Set Timezone to Asia/Kolkata
      ansible.builtin.shell: |
        sudo timedatectl set-timezone Asia/Kolkata
      delegate_to: "34.235.131.96"
      remote_user: "ubuntu"

    - name: Install docker and docker compose
      ansible.builtin.shell: |
        sudo apt-get update -y
        sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
        sudo chmod 777 /var/run/docker.sock
      delegate_to: "34.235.131.96"
      remote_user: "ubuntu"

    - name: Copy All data to ubuntu
      ansible.builtin.copy:
        src: /home/dikshant/Documents/zeerodha-task/Devops-Task-Zeerodha/ops-interview-task-master/
        dest: /home/ubuntu
        owner: ubuntu
        group: ubuntu
        mode: u+rw,g-wx,o-rwx
      delegate_to: "34.235.131.96"
      remote_user: "ubuntu"

    - name: Deploy Dockercompsoe
      ansible.builtin.shell: |
        cd /home/ubuntu
        docker compose up -d
      delegate_to: "34.235.131.96"
      remote_user: "ubuntu"
