version: '3'
services:
  redis:
    image: redis:latest
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - nginx-network
  app:
    image: zeerodha-go:latest
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "3000:3000"
    networks:
      - nginx-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/:/etc/nginx/ssl/ # For SSL certificates
    depends_on:
      - app
    networks:
      - nginx-network

networks:
  nginx-network:
